controller:
  tag: "2.322-jdk11"
  installPlugins:
    - bouncycastle-api:2.25
    - kubernetes:1.30.11
    - workflow-job:2.42
    - workflow-aggregator:2.6
    - credentials-binding:1.27
    - git:4.10.0
    - google-oauth-plugin:1.0.6
    - google-source-plugin:0.4
    - google-kubernetes-engine:0.8.6
    - google-storage-plugin:1.5.4.1
    - blueocean:1.25.2
    - job-dsl:1.78.1
    - configuration-as-code:1.54
    - github-oauth:0.34
    - ansicolor:1.0.1
    - sonar:2.14
    - command-launcher:1.6
    - jacoco:3.3.0
    - pipeline-utility-steps:2.11.0
  additionalExistingSecrets:
    - name: jenkins-config
      keyName: git-app-id
    - name: jenkins-config
      keyName: git-private-key
    - name: jenkins-config
      keyName: git-org-name
    - name: jenkins-config
      keyName: project-id
    - name: jenkins-config
      keyName: jenkins-tf-ksa
    - name: jenkins-config
      keyName: docker-image-repository-url
    - name: jenkins-config
      keyName: helm-image-repository-url
    - name: jenkins-config
      keyName: maven-repository-url
    - name: jenkins-config
      keyName: cluster-name
  JCasC:
    defaultConfig: true
    configScripts:
      plugins-config: |
        unclassified:
          ansiColorBuildWrapper:
            globalColorMapName: "xterm"
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - gitHubApp:
                      id: "github-org"
                      appID: ${jenkins-config-git-app-id}
                      privateKey: ${jenkins-config-git-private-key}
      init-jobs: |
        jobs:
          - script: >
                multibranchPipelineJob('Deploy the application') {
                    factory {
                      workflowBranchProjectFactory {
                          scriptPath('environments/Jenkinsfile')
                      }
                    }
                    branchSources {
                      github {
                          id('23232323')
                          scanCredentialsId('github-org')
                          repoOwner('${jenkins-config-git-org-name}')
                          repository("gcp-environment")
                          buildOriginBranch(true)
                          buildOriginPRMerge(true)
                          includes("dev prod PR*")
                      }
                    }
                    orphanedItemStrategy {
                      discardOldItems {
                          numToKeep(10)
                      }
                    }
                    triggers {
                      cron('@daily')
                    }
                }

          - script: >
                organizationFolder('${jenkins-config-git-org-name}') {
                    triggers {
                      cron('@daily')
                    }
                    organizations {
                        github {
                            repoOwner('${jenkins-config-git-org-name}')
                            apiUri("https://api.github.com")
                            credentialsId('github-org')
                            traits {
                                gitHubBranchDiscovery {
                                  strategyId(1)
                                }
                            }
                        }
                    }
                    projectFactories {
                        workflowMultiBranchProjectFactory {
                            scriptPath("Jenkinsfile")
                        }
                    }
                }
agent:
  tag: 4.11-1-jdk17-preview
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  envVars:
    - name: CLUSTER_NAME
      value: ${jenkins-config-cluster-name}
    - name: IMAGE_REPOSITORY_URL
      value: ${jenkins-config-docker-image-repository-url}
    - name: HELM_IMAGE_REPOSITORY_URL
      value: ${jenkins-config-helm-image-repository-url}
    - name: MAVEN_REPOSITORY_URL
      value: ${jenkins-config-maven-repository-url}
    - name: HELM_EXPERIMENTAL_OCI
      value: "1"
  podTemplates:
    terraform: |
      - name: terraform
        label: terraform-exec
        serviceAccount: "${jenkins-config-jenkins-tf-ksa}"
        containers:
          - name: terraform
            image: "hashicorp/terraform:1.0.10"
            command: "/bin/sh -c"
            alwaysPullImage: false
            args: "cat"
            ttyEnabled: true
            resourceRequestCpu: "100m"
            resourceLimitCpu: "1"
            resourceRequestMemory: "256Mi"
            resourceLimitMemory: "512Mi"

serviceAccount:
  name: cd-jenkins