apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: ${namespace}
spec:
  version: 7.15.2
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false